{
  "formatVersion": "1.1",
  "component": {
    "group": "com.aptokenizer",
    "module": "tokenizer",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "tokenizer-1.1.0.aar",
          "url": "tokenizer-1.1.0.aar",
          "size": 199188,
          "sha512": "9cde0d771c0d34937cc914ba9cf497be88a7e9605bce7f5b4dc5d42ab322dc710a6ef1d593fd01201ee84316eb883bf94e4142c351847c1a155d8885db3ed4d5",
          "sha256": "9f171638026afe8a0536869b21676f860de45e662b27bd566b077739b73f9df0",
          "sha1": "4b9a4bfbfd9424393cecffe1c7d78efc47eb97f4",
          "md5": "4694ab408f4719c806bb5770fe44c1d6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material"
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2026.03.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "tokenizer-1.1.0.aar",
          "url": "tokenizer-1.1.0.aar",
          "size": 199188,
          "sha512": "9cde0d771c0d34937cc914ba9cf497be88a7e9605bce7f5b4dc5d42ab322dc710a6ef1d593fd01201ee84316eb883bf94e4142c351847c1a155d8885db3ed4d5",
          "sha256": "9f171638026afe8a0536869b21676f860de45e662b27bd566b077739b73f9df0",
          "sha1": "4b9a4bfbfd9424393cecffe1c7d78efc47eb97f4",
          "md5": "4694ab408f4719c806bb5770fe44c1d6"
        }
      ]
    }
  ]
}
