{
  "formatVersion": "1.1",
  "component": {
    "group": "com.aptokenizer",
    "module": "tokenizer",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "tokenizer-1.1.1.aar",
          "url": "tokenizer-1.1.1.aar",
          "size": 288598,
          "sha512": "3558edbfdbfea8a2fd00d899f85ac84e5a1f2012097579fc6f7c6bda8bd8536c6eb2d1034021ff7fc57918f85dfe4d10f05e830a098608fbd09720c0935cd929",
          "sha256": "8b24957cf6a18100de962f3049aa4dff4b4006f344c36797ec5cce5ea6bb3d30",
          "sha1": "8cc8bf6b84ea12dd186067c133bb1b63ea8d4381",
          "md5": "9cef157bbd4f187a90e7e811c26cab5c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material"
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.05.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "tokenizer-1.1.1.aar",
          "url": "tokenizer-1.1.1.aar",
          "size": 288598,
          "sha512": "3558edbfdbfea8a2fd00d899f85ac84e5a1f2012097579fc6f7c6bda8bd8536c6eb2d1034021ff7fc57918f85dfe4d10f05e830a098608fbd09720c0935cd929",
          "sha256": "8b24957cf6a18100de962f3049aa4dff4b4006f344c36797ec5cce5ea6bb3d30",
          "sha1": "8cc8bf6b84ea12dd186067c133bb1b63ea8d4381",
          "md5": "9cef157bbd4f187a90e7e811c26cab5c"
        }
      ]
    }
  ]
}
